/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as BuildWithUsRouteImport } from './routes/build-with-us'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as PricingRouteImport } from './routes/pricing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildWithUsRoute = BuildWithUsRouteImport.update({
  id: '/build-with-us',
  path: '/build-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/build-with-us': typeof BuildWithUsRoute
  '/configure': typeof ConfigureRoute
  '/equipment': typeof EquipmentRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/build-with-us': typeof BuildWithUsRoute
  '/configure': typeof ConfigureRoute
  '/equipment': typeof EquipmentRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/build-with-us': typeof BuildWithUsRoute
  '/configure': typeof ConfigureRoute
  '/equipment': typeof EquipmentRoute
  '/pricing': typeof PricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/build-with-us'
    | '/configure'
    | '/equipment'
    | '/pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/build-with-us'
    | '/configure'
    | '/equipment'
    | '/pricing'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/build-with-us'
    | '/configure'
    | '/equipment'
    | '/pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BuildWithUsRoute: typeof BuildWithUsRoute
  ConfigureRoute: typeof ConfigureRoute
  EquipmentRoute: typeof EquipmentRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-with-us': {
      id: '/build-with-us'
      path: '/build-with-us'
      fullPath: '/build-with-us'
      preLoaderRoute: typeof BuildWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  BuildWithUsRoute: BuildWithUsRoute,
  ConfigureRoute: ConfigureRoute,
  EquipmentRoute: EquipmentRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
